# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_position_controller

  joint_trajectory_position_controller:
    type: FollowJointTrajectory
    joints:
      - khi_cx110l_joint1
      - khi_cx110l_joint2
      - khi_cx110l_joint3
      - khi_cx110l_joint4
      - khi_cx110l_joint5
      - khi_cx110l_joint6
    action_ns: follow_joint_trajectory
    default: true